/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{vue,js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#5b2ecc',
        'primary-dark': '#4520a5',
        'primary-light': '#f0ebff',
        'primary-container': '#5b2ecc',
        'on-primary': '#ffffff',
        'on-primary-container': '#ffffff',
        'primary-fixed': '#e8deff',
        'primary-fixed-dim': '#cdbdff',
        'on-primary-fixed': '#20005f',
        'on-primary-fixed-variant': '#4f1bc0',
        'inverse-primary': '#cdbdff',
        'surface-tint': '#673dd8',
        secondary: '#176b5b',
        'secondary-container': '#6cf8bb',
        'on-secondary-container': '#00714d',
        tertiary: '#563400',
        'tertiary-container': '#754900',
        'on-tertiary-container': '#ffb95f',
        error: '#c62828',
        'error-container': '#ffe1e1',
        'on-error-container': '#93000a',
        attention: '#f4a340',
        'attention-light': '#fdf3e3',
        'attention-dark': '#b97a1f',
        success: '#176b5b',
        'success-light': '#e3f2ee',
        'error-light': '#fdecec',
        line: '#e8eaf0',
        background: '#f7f8fc',
        'on-background': '#0f1117',
        surface: '#f7f8fc',
        'on-surface': '#1f2937',
        'surface-bright': '#f7f8fc',
        'surface-dim': '#e9eaf0',
        'surface-container': '#eef0f6',
        'surface-container-low': '#f3f4f9',
        'surface-container-lowest': '#ffffff',
        'surface-container-high': '#e9eaf0',
        'surface-container-highest': '#e2e4ec',
        'surface-variant': '#e9eaf0',
        'on-surface-variant': '#6b7280',
        outline: '#9aa0aa',
        'outline-variant': '#e9eaf0',
        'inverse-surface': '#181c25',
        'inverse-on-surface': '#f5f5f7',
      },
      fontFamily: {
        sans: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['32px', '40px'],
        'display-md': ['28px', '36px'],
        'title-md': ['16px', '24px'],
        'label-md': ['14px', '20px'],
        'body-lg': ['16px', '24px'],
        'body-sm': ['14px', '20px'],
      },
      spacing: {
        sidebar: '280px',
        gutter: '24px',
        sm: '8px',
        md: '16px',
        xs: '4px',
      },
      maxWidth: {
        content: '1040px',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        card: '14px',
        full: '9999px',
      },
      boxShadow: {
        soft: '0 1px 3px rgba(16,24,40,0.04), 0 1px 2px rgba(16,24,40,0.03)',
        card: '0 1px 3px rgba(16,24,40,0.05), 0 4px 16px rgba(16,24,40,0.04)',
      },
    },
  },
  plugins: [],
}

