/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{vue,js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        /* Tokens sémantiques = variables CSS (définies dans style.css, :root / .dark)
           → le mode sombre bascule automatiquement toutes les surfaces/textes. */
        primary: 'rgb(var(--c-primary) / <alpha-value>)',
        'primary-dark': 'rgb(var(--c-primary-dark) / <alpha-value>)',
        'primary-light': 'rgb(var(--c-primary-light) / <alpha-value>)',
        'primary-container': 'rgb(var(--c-primary) / <alpha-value>)',
        'on-primary': '#ffffff',
        'on-primary-container': '#ffffff',
        'primary-fixed': 'rgb(var(--c-primary-light) / <alpha-value>)',
        'primary-fixed-dim': 'rgb(var(--c-primary-fixed-dim) / <alpha-value>)',
        'on-primary-fixed': 'rgb(var(--c-on-primary-fixed) / <alpha-value>)',
        'on-primary-fixed-variant': 'rgb(var(--c-primary-dark) / <alpha-value>)',
        'inverse-primary': 'rgb(var(--c-inverse-primary) / <alpha-value>)',
        'surface-tint': 'rgb(var(--c-primary) / <alpha-value>)',
        secondary: '#176b5b',
        'secondary-container': '#6cf8bb',
        'on-secondary-container': '#00714d',
        tertiary: '#563400',
        'tertiary-container': '#754900',
        'on-tertiary-container': '#ffb95f',
        error: '#c62828',
        'error-container': 'rgb(var(--c-error-container) / <alpha-value>)',
        'on-error-container': '#ffb4ab',
        attention: '#f4a340',
        'attention-light': 'rgb(var(--c-attention-light) / <alpha-value>)',
        'attention-dark': '#b97a1f',
        success: '#176b5b',
        'success-light': 'rgb(var(--c-success-light) / <alpha-value>)',
        'error-light': 'rgb(var(--c-error-light) / <alpha-value>)',
        line: 'rgb(var(--c-line) / <alpha-value>)',
        background: 'rgb(var(--c-background) / <alpha-value>)',
        'on-background': 'rgb(var(--c-on-surface) / <alpha-value>)',
        surface: 'rgb(var(--c-surface) / <alpha-value>)',
        'on-surface': 'rgb(var(--c-on-surface) / <alpha-value>)',
        'surface-bright': 'rgb(var(--c-surface-bright) / <alpha-value>)',
        'surface-dim': 'rgb(var(--c-surface-dim) / <alpha-value>)',
        'surface-container': 'rgb(var(--c-surface-container) / <alpha-value>)',
        'surface-container-low': 'rgb(var(--c-surface-container-low) / <alpha-value>)',
        'surface-container-lowest': 'rgb(var(--c-surface-container-lowest) / <alpha-value>)',
        'surface-container-high': 'rgb(var(--c-surface-container-high) / <alpha-value>)',
        'surface-container-highest': 'rgb(var(--c-surface-container-highest) / <alpha-value>)',
        'surface-variant': 'rgb(var(--c-surface-variant) / <alpha-value>)',
        'on-surface-variant': 'rgb(var(--c-on-surface-variant) / <alpha-value>)',
        outline: 'rgb(var(--c-outline) / <alpha-value>)',
        'outline-variant': 'rgb(var(--c-outline-variant) / <alpha-value>)',
        'inverse-surface': 'rgb(var(--c-inverse-surface) / <alpha-value>)',
        'inverse-on-surface': 'rgb(var(--c-inverse-on-surface) / <alpha-value>)',
      },
      fontFamily: {
        sans: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['32px', '40px'],
        'display-md': ['28px', '36px'],
        'title-md': ['16px', '24px'],
        'label-md': ['14px', '20px'],
        'body-lg': ['16px', '24px'],
        'body-sm': ['14px', '20px'],
      },
      spacing: {
        sidebar: '280px',
        gutter: '24px',
        sm: '8px',
        md: '16px',
        xs: '4px',
      },
      maxWidth: {
        content: '1040px',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        card: '14px',
        full: '9999px',
      },
      boxShadow: {
        soft: '0 1px 3px rgba(16,24,40,0.04), 0 1px 2px rgba(16,24,40,0.03)',
        card: '0 1px 3px rgba(16,24,40,0.05), 0 4px 16px rgba(16,24,40,0.04)',
      },
    },
  },
  plugins: [],
}

